-- Run as ACCOUNTADMIN once, then use SYSADMIN for normal objects.
-- Replace placeholder values before execution.

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS PIPELINE_DB;
CREATE SCHEMA IF NOT EXISTS PIPELINE_DB.RAW;
CREATE WAREHOUSE IF NOT EXISTS PIPELINE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- The integration lets Snowflake read the S3 bucket without storing AWS keys.
-- Replace the allowed S3 location with your real bucket and prefix.
CREATE STORAGE INTEGRATION IF NOT EXISTS PIPELINE_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/<SNOWFLAKE_S3_ROLE>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<BUCKET_NAME>/raw/');

USE ROLE SYSADMIN;
USE DATABASE PIPELINE_DB;
USE SCHEMA RAW;
USE WAREHOUSE PIPELINE_WH;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE TABLE STAGING_EVENTS (
  source_file STRING,
  record_type STRING,
  payload VARIANT,
  loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMERS (
  customer_id NUMBER,
  full_name STRING,
  email STRING,
  city STRING,
  updated_at TIMESTAMP_NTZ,
  loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ORDERS (
  order_id NUMBER,
  customer_id NUMBER,
  order_date DATE,
  amount NUMBER(12,2),
  status STRING,
  loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PIPELINE_ERRORS (
  source_file STRING,
  payload VARIANT,
  error_message STRING,
  created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
