USE ROLE SYSADMIN;
USE DATABASE PIPELINE_DB;
USE SCHEMA RAW;
USE WAREHOUSE PIPELINE_WH;

CREATE OR REPLACE STREAM STAGING_EVENTS_STREAM ON TABLE STAGING_EVENTS;

CREATE OR REPLACE TABLE TABLE_1_CUSTOMERS (
  customer_id NUMBER,
  full_name STRING,
  email STRING,
  city STRING,
  updated_at TIMESTAMP_NTZ,
  loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TABLE_2_ORDERS (
  order_id NUMBER,
  customer_id NUMBER,
  order_date DATE,
  amount NUMBER(12,2),
  status STRING,
  loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PIPELINE_ERRORS (
  source_file STRING,
  payload VARIANT,
  error_message STRING,
  created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TASK ROUTE_STAGING_TASK
  WAREHOUSE = PIPELINE_WH
  SCHEDULE = 'USING CRON 0/5 * * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('PIPELINE_DB.RAW.STAGING_EVENTS_STREAM')
AS
BEGIN
  INSERT INTO TABLE_1_CUSTOMERS (customer_id, full_name, email, city, updated_at)
  SELECT
    TRY_TO_NUMBER(payload[0]::STRING), payload[1]::STRING, payload[2]::STRING,
    payload[3]::STRING, TRY_TO_TIMESTAMP_NTZ(payload[4]::STRING)
  FROM STAGING_EVENTS_STREAM
  WHERE record_type = 'CUSTOMER' AND METADATA$ACTION = 'INSERT';

  INSERT INTO TABLE_2_ORDERS (order_id, customer_id, order_date, amount, status)
  SELECT
    TRY_TO_NUMBER(payload[0]::STRING), TRY_TO_NUMBER(payload[1]::STRING),
    TRY_TO_DATE(payload[2]::STRING), TRY_TO_DECIMAL(payload[3]::STRING, 12, 2),
    payload[4]::STRING
  FROM STAGING_EVENTS_STREAM
  WHERE record_type = 'ORDER' AND METADATA$ACTION = 'INSERT';

  INSERT INTO PIPELINE_ERRORS (source_file, payload, error_message)
  SELECT source_file, payload, 'Unsupported record type'
  FROM STAGING_EVENTS_STREAM
  WHERE record_type = 'UNKNOWN' AND METADATA$ACTION = 'INSERT';
END;

-- Tasks are created suspended by default. Resume after testing:
ALTER TASK ROUTE_STAGING_TASK RESUME;

-- Verification:
-- SELECT * FROM TABLE_1_CUSTOMERS ORDER BY customer_id;
-- SELECT * FROM TABLE_2_ORDERS ORDER BY order_id;
-- SELECT * FROM PIPELINE_ERRORS;
